# These are supported funding model platforms

custom: ['https://www.fiverr.com/creativitas/design-modern-headless-online-shop-ecommerce-website','https://www.fiverr.com/creativitas/create-your-website-with-new-technology','https://www.fiverr.com/creativitas/design-your-website-with-progresive-web-application']
